### ISSUE TITLE
findAttribute unexpectedly returns `Void?` instead of DefaultAttribute

### ISSUE THREAD

**Issue by stevenbrix** [tristanlabelle/swift-dotnetmetadata#12]
![image](https://github.com/tristanlabelle/swift-dotnetmetadata/assets/9649518/882d9619-b3be-4676-9578-741f83b1e9e7)

**Comment by tristanlabelle** [comment]
It's a little weird, I agree. I also considered returning `DefaultAttribute`, but this would be an empty struct since the attribute doesn't store any information: https://learn.microsoft.com/en-us/uwp/api/windows.foundation.metadata.defaultattribute . You couldn't get the interface definition from it. The return value is basically a boolean hidden in `Void?` shape.

The reason for this is that it allows `findAttribute(OverloadAttribute.self)` and other single-parameter attributes to return a `String` directly instead of an `OverloadAttribute` struct that has a String field. I wouldn't consider this a bug, but I'm not attached to this design decision and I'm open to it changing.

**Comment by tristanlabelle** [comment]
Updated to returning the attribute type struct in https://github.com/tristanlabelle/swift-dotnetmetadata/commit/b072544df3dbaaacdbc0c19e91896ee45b74bd07
