### ISSUE TITLE
accessing properties on types causes assembly loads

### ISSUE THREAD

**Issue by stevenbrix** [tristanlabelle/swift-dotnetmetadata#13]
i would expect that once i've loaded an assembly, it's resolved all dependent assemblies and ensured that they are resolvable. the lazy loading of the assemblies makes it easy to run into issues further down the road when using this API. it also seems to require all APIs to be marked with `throws` which makes it cumbersome to use

**Comment by tristanlabelle** [comment]
That is a sensible expectation, but the decision is by design for this implementation. I think there are two fundamental ways to design this library:

1. Load everything ahead of time in an in-memory representation that is fully validated, such that no errors can happen when accessing members.
2. Load everything lazily and raise errors as they are encountered.

1's pros is the API has a single throwing point and the assembly file handle can be closed after reading. 1's cons is that it is only suitable for batch operation since it incurs a large upfront cost, especially for assemblies like `Windows.winmd` or `mscorlib.dll`. It is also difficult to report multiple issues rather than only the first encountered, and it might require implementing larger chunks of the file format at once to be able to return a value.

Conversely, 2's pros is that it supports building more targeted tools that don't need to load everything without incurring a large up-front cost, it allows handling assemblies having some bad data somewhere and reporting errors piecemeal as they are encountered, makes it easier to implement part of the file format. 2's cons are that all members become throwing functions and the assembly must be kept open (but it can be memory-mapped).

I wanted to make this library usable in streaming scenarios, with recoverable just-in-time errors so I went with option 2. The design also mimics `System.Reflection`.

I don't think hybrid approaches would make sense since it would be difficult to isolate throwing functions to just a few relevant places.
